apiVersion: apps/v1
kind: Deployment
metadata:
  name: gode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gode
  template:
    metadata:
      labels:
        app: gode
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: gode
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "1a4f623d-6f3b-4534-be54-3bdcb98aecd9"
        - name: Vless_Path
          value: "/vl53355"
        - name: Vmess_UUID
          value: "66f9d58b-0177-4172-bb67-aaf1ea3fe62b"
        - name: Vmess_Path
          value: "/vm66226"
        - name: Share_Path
          value: "/v2link"
